/**
 * `bungae init` — Generate a starter `bungae.config.{ts,js}` based on the
 * project's `package.json`. Auto-detects Expo and wraps with `withExpo()`
 * when applicable.
 *
 * Mirrors how Metro / Expo / Vite scaffold their config files: detection runs
 * once at init time, results in a checked-in static file. After that, the
 * config file is the single source of truth.
 */

import { existsSync, writeFileSync, readFileSync } from 'fs';
import { join } from 'path';

import { detectExpo } from '../src/bundler/zts-bundler/withExpo';

interface InitOptions {
  cwd: string;
  js: boolean;
  force: boolean;
}

const TS_BANNER = `// bungae.config.ts — generated by \`bungae init\`. Edit freely.\n`;
const JS_BANNER = `// bungae.config.js — generated by \`bungae init\`. Edit freely.\n`;

function tsTemplate(opts: { expo: boolean }): string {
  const importLine = opts.expo
    ? `import { defineConfig, withExpo } from 'bungae';`
    : `import { defineConfig } from 'bungae';`;
  const open = opts.expo ? 'withExpo(defineConfig({' : 'defineConfig({';
  const close = opts.expo ? '}));' : '});';

  return `${TS_BANNER}
import { dirname } from 'path';
import { fileURLToPath } from 'url';

${importLine}

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export default ${open}
  root: __dirname,
  entry: 'index.js',
  bundler: 'zts',
${close}
`;
}

function jsTemplate(opts: { expo: boolean }): string {
  const importLine = opts.expo
    ? `const { defineConfig, withExpo } = require('bungae');`
    : `const { defineConfig } = require('bungae');`;
  const open = opts.expo ? 'withExpo(defineConfig({' : 'defineConfig({';
  const close = opts.expo ? '}));' : '});';

  return `${JS_BANNER}
${importLine}

module.exports = ${open}
  root: __dirname,
  entry: 'index.js',
  bundler: 'zts',
${close}
`;
}

function ensureScript(pkgPath: string): string[] {
  const added: string[] = [];
  if (!existsSync(pkgPath)) return added;
  let raw: string;
  try {
    raw = readFileSync(pkgPath, 'utf8');
  } catch {
    return added;
  }
  let pkg: any;
  try {
    pkg = JSON.parse(raw);
  } catch {
    return added;
  }
  pkg.scripts ??= {};
  if (!pkg.scripts['start:bungae']) {
    pkg.scripts['start:bungae'] = 'bungae start';
    added.push('start:bungae');
  }
  if (!pkg.scripts['build:bungae']) {
    pkg.scripts['build:bungae'] = 'bungae bundle';
    added.push('build:bungae');
  }
  if (added.length > 0) {
    writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
  }
  return added;
}

function ensureGitignore(cwd: string): boolean {
  const gitignorePath = join(cwd, '.gitignore');
  if (!existsSync(gitignorePath)) return false;
  let content: string;
  try {
    content = readFileSync(gitignorePath, 'utf8');
  } catch {
    return false;
  }
  if (
    content.split(/\r?\n/).some((line) => line.trim() === '.bungae' || line.trim() === '.bungae/')
  ) {
    return false;
  }
  const trailing = content.endsWith('\n') ? '' : '\n';
  writeFileSync(gitignorePath, `${content}${trailing}.bungae/\n`);
  return true;
}

export function runInit(options: InitOptions): void {
  const { cwd, js, force } = options;
  const configFile = js ? 'bungae.config.js' : 'bungae.config.ts';
  const configPath = join(cwd, configFile);

  if (existsSync(configPath) && !force) {
    console.error(`error: ${configFile} already exists. Re-run with --force to overwrite.`);
    process.exit(1);
  }

  const expo = detectExpo(cwd);
  const template = js ? jsTemplate({ expo: !!expo }) : tsTemplate({ expo: !!expo });

  writeFileSync(configPath, template);

  console.log(`✓ wrote ${configFile}`);
  if (expo) {
    console.log(`  detected ${expo.name}@${expo.version} → wrapped with withExpo()`);
  } else {
    console.log('  no expo dependency → vanilla React Native config');
  }

  // package.json scripts
  const addedScripts = ensureScript(join(cwd, 'package.json'));
  for (const s of addedScripts) {
    console.log(`✓ added "${s}" to package.json scripts`);
  }

  // .gitignore
  if (ensureGitignore(cwd)) {
    console.log('✓ added .bungae/ to .gitignore');
  }

  console.log('\nDone. Try `bungae start` or `bungae bundle --platform ios`.');
}
